### PR TITLE
Annotations json

### PR DESCRIPTION
**Pull request by ivica3730k**
Implemented all functions for AnnotationModel and written all unit tests.
Created all comments for Doxygen.
Created exceptions to enhance user experience.
Checked that code complies with The Coding Styleguide.
Changed build script ( removed rm lines that were trying to delete files already deleted).
Made getSelected() method of ClassModel return empty string not to cause issues if overseen in future.

Note: When merging DO not use LinkedList from this branch as it is outdated.

### CODE REVIEW

**Comment by PetarPeychev** [comment]
Style Guide clarifications with references to the relevant sections:
- ClassModel::getSelected() has an opening curly bracket on the same line. (8.9)
- createPoints(int multiplier) in the tests same issue. (8.9)
- compareShapes(Shape &a, Shape &b) in the tests same issue. (8.9)
- Keywords, such as 'for', 'while' and 'if' shouldn't have space after them. (8.10, 8.11, 8.12, 8.13, 8.14)
- In control-flow constructs where the opening curly bracket is on the same line as the initial part of the construct, there should be a space before the curly bracket. (8.10, 8.11, 8.12, 8.13, 8.14)
- Commas should always be followed by a space. This is not being done in function calls in tests. (8.16)

**Comment by PetarPeychev** [comment]
You've mentioned the LinkedList class is outdated in the pull request, but the opposite seems to be true. In this branch, the issue #24 is resolved, while it is hasn't been in the development branch. So is the LinkedList outdated or not?

**Comment by ivica3730k** [comment]
Look at the latest commit from this branch. I have implemented fix and improvement to linked list. Using size_t for indexes, removing checks for is index positive as size_t is unsigned type.

I will do code refactoring to fit the style guide.

**Comment by PetarPeychev** [comment]
> Look at the latest commit from this branch. I have implemented fix and improvement to linked list. Using size_t for indexes, removing checks for is index positive as size_t is unsigned type.
> 
> I will do code refactoring to fit the style guide.

So in that case, the note saying we shouldn't use the LinkedList when merging is wrong. Also, you seem to have done find and replace of int with size_t and this has messed up a lot of comments, which contain words with the letters 'int' in them. It's quite funny.

**Comment by ivica3730k** [comment]
> > Look at the latest commit from this branch. I have implemented fix and improvement to linked list. Using size_t for indexes, removing checks for is index positive as size_t is unsigned type.
> > I will do code refactoring to fit the style guide.
> 
> So in that case, the note saying we shouldn't use the LinkedList when merging is wrong. Also, you seem to have done find and replace of int with size_t and this has messed up a lot of comments, which contain words with the letters 'int' in them. It's quite funny.

I havent just did rename of int to size_t, I also fixed errors which were thrown by unit tests.  I will remove comment not to merge linked list. Problem is that the code from branch quicksort is not present in the development, but status on quicksort says merged

**Pull request merged**
